### ISSUE TITLE
Model.find does not work with sqlite3

### ISSUE THREAD

**Issue by toxix** [inossidabile/protector-cancan#4]
the following is raising an error:

``` ruby
  User.restrict!(User.all.first).find(1)
```

```
SQLite3::RangeException: bind or column index out of range: SELECT "users".* FROM "users" WHERE "users"."id" = 1 LIMIT 1
```

Reproduce: 
adding in to the Gemfile

``` ruby
gem 'protector', github: 'inossidabile/protector'
```

```
rails g scaffold User name:string admin:boolean
```

and adding two users one with admin one without admin

``` ruby
class User < ActiveRecord::Base

protect do |user|
  if user.admin?
    can :read
  else
    scope {where(id: user.id)}
    can :read
  end
end

end
```

Workaround

``` ruby
  @user = User.restrict!(User.all.first).find_by(id: params[:id])
```

or using non restricted version

``` ruby
  @user = User.find(params[:id])
```

**Comment by inossidabile** [comment]
So the problem is with Protector itself and it doesn't relate to CanCan right? I'm just not entirely sure why you posted it here. Should I move it to Protector's main repo?

**Comment by toxix** [comment]
@snossidabile: Feel free to move. It was a moment of abstraction because I'm using this repro in my Aplication, but Protector's main repro has the same error.

I am rails nb, after debugging it seems like exec_queries_with_protector(*args) function (lib/protector/adapters/active_record/relation.rb:123) is not setting the where condition/binding of parameters in the right manner.

**Comment by toxix** [comment]
can you update protector-cancan with the fix you did on https://github.com/inossidabile/protector/issues/29#ref-commit-bf96e61 thx.

**Comment by inossidabile** [comment]
It's not required since `protector-cancan` reference it by open dependency. Just add direct dependency to protector linked from GH like this:

`gem 'protector', github: 'inossidabile/protector'`

Then run

`bundle install`

**Comment by toxix** [comment]
fine. :) thx. for the hint.
